name: Main Release

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  release:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Setup Yarn
        run: |
          mkdir -p .yarn/releases
          npm install -g corepack
          corepack enable
          corepack prepare yarn@3.7.0 --activate
          cp ~/.cache/node/corepack/v1/yarn/3.7.0/yarn.js .yarn/releases/yarn-3.7.0.cjs
      
      - name: Install dependencies
        run: yarn install
      
      - name: Build
        run: yarn build
      
      - name: Generate oclif manifest
        run: yarn oclif manifest
      
      - name: Get version
        id: version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.version }}
          release_name: Release v${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
      
      - name: Pack for platforms
        run: |
          mkdir -p dist/tarballs
          NODE_ENV=production yarn install
          echo "Running oclif pack..."
          yarn oclif pack tarballs --no-xz
          echo "Checking tarballs directory..."
          ls -la dist/tarballs
          echo "Renaming tarballs..."
          cd dist/tarballs
          shopt -s nullglob
          for f in *.tar.gz; do
            if [ -f "$f" ]; then
              echo "Processing $f..."
              mv "$f" "hom-cli-$(echo $f | sed 's/.*-v\(.*\)-.*/\1/')-${{ runner.os }}.tar.gz"
            else
              echo "No .tar.gz files found in dist/tarballs"
              exit 1
            fi
          done
      
      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/tarballs/
          asset_name: hom-cli-${{ steps.version.outputs.version }}.tar.gz
          asset_content_type: application/gzip
      
      - name: Publish to npm
        run: yarn npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      
      - name: Update Homebrew formula
        run: |
          ./scripts/update-homebrew.sh
        env:
          HOMEBREW_GITHUB_TOKEN: ${{ secrets.HOMEBREW_GITHUB_TOKEN }} 