name: Test Build

on:
  push:
    branches-ignore:
      - main
      - develop

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Setup Yarn
        run: |
          mkdir -p .yarn/releases
          npm install -g corepack
          corepack enable
          corepack prepare yarn@3.7.0 --activate
          cp ~/.cache/node/corepack/v1/yarn/3.7.0/yarn.js .yarn/releases/yarn-3.7.0.cjs
      
      - name: Install dependencies
        run: yarn install
      
      - name: Build
        run: yarn build
      
      - name: Test tarball creation
        run: |
          # Create dist directory
          mkdir -p dist
          
          # Install oclif globally for CLI access
          echo "Installing @oclif/cli globally..."
          yarn global add @oclif/cli
          
          # Add global yarn bin to PATH
          export PATH="$(yarn global bin):$PATH"
          
          echo "Running oclif pack..."
          oclif pack tarballs
          
          # Show what was created
          echo "Contents of dist directory:"
          ls -R dist
          
          # Check for tarballs
          if ! find dist -name "*.tar.gz" -type f | grep -q .; then
            echo "No tarballs were created"
            exit 1
          fi 