name: Test Build

on:
  push:
    branches-ignore:
      - main
      - develop

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Setup Yarn
        run: |
          mkdir -p .yarn/releases
          npm install -g corepack
          corepack enable
          corepack prepare yarn@3.7.0 --activate
          cp ~/.cache/node/corepack/v1/yarn/3.7.0/yarn.js .yarn/releases/yarn-3.7.0.cjs
      
      - name: Install dependencies
        run: yarn install
      
      - name: Build
        run: yarn build
      
      - name: Generate oclif manifest
        run: yarn oclif manifest
      
      - name: Test tarball creation
        run: |
          # Create dist directory
          mkdir -p dist/tarballs
          
          # Create tarball using yarn pack in current directory
          echo "Creating tarball..."
          yarn pack
          sleep 1  # Add a small delay to ensure file is written
          
          # Show what was created
          echo "Files in current directory:"
          ls -la package*
          
          # Copy and remove the package
          cp package.tgz dist/tarballs/hom-cli.tgz && rm package.tgz
          
          # Show what was created
          echo "Contents of dist directory:"
          ls -R dist
          
          # Check for tarballs
          if ! find dist/tarballs -name "*.tgz" -type f | grep -q .; then
            echo "No tarballs were created"
            echo "Contents of all relevant directories:"
            find . -name "*.tgz" -type f
            exit 1
          fi
          
          # Upload artifacts for inspection if needed
          echo "Creating artifact of dist directory..."
          tar -czf dist-contents.tar.gz dist/ 